export enum Redux {
  commentChapter = 'commentChapter',
  commentForum = 'commentForum',
  user = 'user',
  auth = 'auth',
  loading = 'loading',
  app = 'app',
  alert = 'alert',
  theme = 'theme',
  comic = 'comic',
  topic = 'topic',
  chat = 'chat',
  forum = 'forum',
  rating = 'rating',
}
